export const Urls = {
  admin: {
    index: '/admin/',
    login: '/admin/login/',
    logout: '/admin/logout/',
    password_change: '/admin/password_change/',
    password_change_done: '/admin/password_change/done/',
    jsi18n: '/admin/jsi18n/',
    view_on_site: (content_type_id: number, object_id: string) => `/admin/r/${content_type_id}/${object_id}/`,
    app_list: (app_label: string) => `/admin/${app_label}/`,
  },
  sso_server: {
    sso_request_token: '/sso/request-token/',
    sso_authorize: '/sso/authorize/',
    sso_verify: '/sso/verify/',
  },
  oauth2_provider: {
    authorize: '/oauth2/authorize/',
    token: '/oauth2/token/',
    revoke_token: '/oauth2/revoke_token/',
    introspect: '/oauth2/introspect/',
    list: '/oauth2/applications/',
    register: '/oauth2/applications/register/',
    detail: (pk: string) => `/oauth2/applications/${pk}/`,
    delete: (pk: string) => `/oauth2/applications/${pk}/delete/`,
    update: (pk: string) => `/oauth2/applications/${pk}/update/`,
    authorized_token_list: '/oauth2/authorized_tokens/',
    authorized_token_delete: (pk: string) => `/oauth2/authorized_tokens/${pk}/delete/`,
  },
  storage: {
    create_template: '/storage/template/new',
    add_template: '/storage/template/add',
    check_tem_title: (title: string) => `http://localhost:9001/api/v2/storage/template?title=${title}`,
    check_template: (tid: number) => `/storage/template/${tid}/check`,
    edit_template: (tid: number) => `/storage/template/${tid}/edit`,
    upload_data: '/storage/data/new',
    add_data: '/storage/data/add',
    show_template_review: (page: number, state: number) => `/storage/template/review/${page}/${state}`,
    edit_data: (did: number) => `/storage/data/${did}/edit`,
    // show_data: (did: number) => `/storage/data/${did}`,
    show_data: (did: number) => `/show_data?dataID=${did}`,
    export_data: '/export',
    review_data_state: (state: string, page: number) => `/storage/data/review/${state}/page/${page}`,
    review_data_page: (page: number) => `/storage/data/review/page/${page}`,
    review_data: '/storage/data/review/',
    register_doi: '/storage/data/registerdoi',
    doi_list: '/storage/data/doilist',
    doi_detail: (did: number) => `/storage/data/doilist/detail/${did}`,
    doi_link: (doi: string) => `/storage/data/doi/${doi}`,
    data_score: '/storage/data/score',
    review_data2: '/storage/data/review2/',
    edit_data_new: '/storage/edit_data/',
    check_snippet:'/storage/check_snippet/',
    edit_snippet:'/storage/edit_snippet/',
  },
  account: {
    login: '/account/login/',
    login_18: 'http://nmdms.ustb.edu.cn',
    logout: '/account/logout/',
    register: '/account/register/',
    reset_request: '/account/reset_password_request',
    reset_password: '/account/reset_password',
    verify_email: '/account/verify_email',
    notifications_page: (page: number) => `/account/notifications/page/${page}`,
    notifications: '/feedback_list',
    my_info: '/account/me',
    my_data: '/account/me/data',
    upload_history_data: (history_id: number) => `/account/me/uploads/${history_id}`,
    upload_history_state: (state: string, page: number) => `/account/me/uploads/${state}/page/${page}`,
    upload_history_page: (page: number) => `/account/me/uploads/page/${page}`,
    upload_history: '/account/me/uploads/',
    my_templates_state: (state: string, page: number) => `/account/me/templates/${state}/page/${page}`,
    my_templates_page: (page: number) => `/account/me/templates/page/${page}`,
    my_templates: '/account/me/templates/',
    user_list: '/account/users/',
    user_permissions: (username: string) => `/account/users/${username}/permissions`,
  },
  service: {
    service_sub: '/service/sub/',
    service_recommend: '/service/sub/recommend/',
  },
  search: {
    expr: '/search/expr',
    index: '/search/',
  },
  analytics: {
    index: '/analytics/',
    project_analytics: '/project_analytics',
  },

  templates: {
    view_template_evalution: (template_id: number) => `/api/cert/templates/view_score/${template_id}`,
  },

  ticketing: {
    show_ticket: (ticket_id: number) => `/ticketing/tickets/${ticket_id}`,
    create_ticket: '/submit_feedback',
    list_tickets: '/ticketing/list_tickets/',
  },
  task: {
    index: '/task/',
  },
  gphase: {
    index: '/Gphase/',
    download_model: '/Gphase/downloadModel/',
    download_result: '/Gphase/downloadResult/',
    calculate: '/Gphase/calculate/',
    entry_system: '/Gphase/entrySystem/',
  },
  image_search: {
    index: '/image_search/index',
    query: '/image_search/query',
  },
  api_v1_storage: {
    material_categories: '/api/v1/storage/material/categories',
    material_category_one: (cid: number) => `/api/v1/storage/material/category/${cid}`,
    material_category_children: (cid: number) => `/api/v1/storage/material/category/${cid}/children`,
    material_category_tree: '/api/v1/storage/material/category/tree',
    templates: '/api/v1/storage/templates',
    template_one: (tid: number) => `/api/v1/storage/template/${tid}`,
    template_data: '/api/v1/storage/template/data', // 返回的是data
    data_metas: '/api/v1/storage/data/metas',
    data_templates: '/api/v1/storage/data/templates', // 返回的是template
    data_meta_one: (mid: number) => `/api/v1/storage/data/meta/${mid}`,
    template_file: (tid: number) => `/api/v1/storage/file/template/${tid}/export`,
    uploaded_file: '/api/v1/storage/file/upload',
    check_file: '/api/v1/storage/file/verify',
    data_export: '/api/v1/storage/file/dataset/export',
    data_content_file: '/api/v1/storage/file/data/content',
    // data_content_images: '/api/v1/storage/file/data/content/images',
    retract_data: (history_id: number) => `/api/v1/storage/data/histories/${history_id}`,
    data_doi_single: (did: number) => `/api/v1/storage/data/doi/${did}`,
    data_dois: '/api/v1/storage/data/dois',
    doi_review: '/api/v1/storage/data/doi/review',
    data_score: (did: number) => `/api/v1/storage/data/score/${did}`,
    get_material_projects: '/api/v1/storage/projects',
    get_projects_all: '/api/v1.1/storage/projects/all',
    get_material_project: (project_id: string) => `/api/v1/storage/projects/${project_id}`,
    get_material_subjects: (project_id: string) => `/api/v1/storage/projects/${project_id}/subjects`,
    get_user_material_subjects: '/api/v1.1/storage/projects/',
    create_material_projects: '/api/v1.1/storage/projects/create',
    delete_subject: (project_id: string, subject_id: string) => `/api/v1.1/storage/projects/${project_id}/subjects/${subject_id}`,
    specific_material_project: (project_id: string) => `/api/v1/storage/v1/projects/${project_id}`,
    create_material_subjects: (project_id: string) => `/api/v1.1/storage/projects/${project_id}/subjects`,
    specific_material_subject: (project_id: string, subject_id: string) => `/api/v1/storage/v1/projects/${project_id}/subjects/${subject_id}`,
    oauth2_templates: '/api/v1/storage/o/templates',
    oauth2_templates_one: (tid: number) => `/api/v1/storage/o/templates/${tid}`,
    oauth2_material_category_tree: '/api/v1/storage/o/material/category/tree',
    oauth2_material_projects: '/api/v1/storage/o/projects/',
  },
  api_v1_1_storage: {
    data_full: '/api/v1.1/storage/data/full',
    o_data_full: '/api/v1.1/storage/o/data/full',
    material_project_query: '/api/v1.1/storage/projects/search/',
    project_all: '/api/v1.1/storage/projects/all',
    specific_material_project: (project_id: string) => `/api/v1.1/storage/projects/${project_id}`,
    get_project_analytics: (project_id: string) => `/api/v1/analytics/projects/${project_id}/stat`,
    get_subject_analytics: (project_id: string, subject_id: string) => `/api/v1/analytics/projects/${project_id}/subjects/${subject_id}/stat`,
    projects_analytics_info: '/api/v1/analytics/projects/info',
  },
  api_v1_account: {
    session_api: '/api/v1/account/user/session/',
    get_captcha: '/api/v1/account/captcha/',
    reset_password_request: '/api/v1/account/user/password/reset_request/',
    reset_password: '/api/v1/account/user/password/',
    resend_verification_email: '/api/v1/account/user/email_verification/',
    user_list: '/api/v1/account/users/',
    subject_users: (subject_id: string) => `/api/v1/account/users/subjects/${subject_id}/subject_users`,
    user_permissions: (username: string) => `/api/v1/account/users/${username}/permissions/`,
    get_user_material_subjects: (username: string) => `/api/v1/account/users/${username}/subjects`,
    user_info: '/api/v1/account/user/info',
    user_resource: (username: string) => `/api/v1/account/users/${username}/`,
    user_avatar: (username: string) => `/api/v1/account/users/${username}/avatar/`,
    notification_list: '/api/v1/account/notifications/',
    notification_resource: (n_id: number) => `/api/v1/account/notifications/${n_id}/`,
    oauth2_user_info: '/api/v1/account/o/user/info',
    oauth2_image_count: '/api/v1/account/o/user/image_count',
    subject_members: (subject_id: string) => `/api/v1/account/users/subjects/${subject_id}/subject_users`,
    move_out_member: (subject_id: string) => `/api/v1/account/users/subjects/${subject_id}/subject_users`,
  },
  api_v1_service: {
    sub_class: '/api/v1/service/sub/class/',
    sub_tag: '/api/v1/service/sub/tag/',
    sub_user: '/api/v1/service/sub/user/',
    recommend: '/api/v1/service/recommend/',
    online_user_counts: '/api/v1/service/user/counts',
    user_visits: '/api/v1/service/user/visits',
    thesaurus_search: '/thesaurus/api/v1/service/thesaurus/search',//词库搜索
    frontend_static:'/api/v1/service/frontend/static', // 静态资源
  },
  api_v1_search: {
    group_query: '/api/v1/search/group',
    query: '/api/v1/search/',
  },
  api_v1_analytics: {
    index: '/api/v1/analytics/',
    query_class: (cid: number) => `/api/v1/analytics/class/${cid}`,
    query_data: (did: number) => `/api/v1/analytics/data/${did}`,
    query_template: (tid: number) => `/api/v1/analytics/template/${tid}`,
    trend: '/api/v1/analytics/trend',
    trend_of_class: (cid: number) => `/api/v1/analytics/trend/${cid}`,
    trend_of_project: (pid: string) => `/api/v1/analytics/trend/projects/${pid}`,
    trend_of_subject: (pid: string, sid: string) => `/api/v1/analytics/trend/projects/${pid}/subjects/${sid}`,
    project_analystics: (project_id: string) => `/api/v1/analytics/projects/${project_id}/stat`,
    subject_analystics: (project_id: string, subject_id: string) => `/api/v1/analytics/projects/${project_id}/subjects/${subject_id}/stat`,
  },
  api_v1_ticketing: {
    create_ticket: '/api/v1/ticketing/create_ticket',
    reply: '/api/v1/ticketing/reply',
    close_ticket: '/api/v1/ticketing/close_ticket',
    finish_ticket: '/api/v1/ticketing/finish_ticket',
    upload_file: '/api/v1/ticketing/upload_file',
    upload_image: '/api/v1/ticketing/upload_image',
    tickets: '/api/v1/ticketing/tickets',
    topic_choice: '/api/v1/ticketing/topic_choices',
    ticket_details: (id: number) => `/api/v1/ticketing/ticket/${id}`,
    ticket_reply: '/api/v1/ticketing/reply',
    ticket_change_status: (id: number) => `/api/v1/ticketing/ticket/${id}`,
  },
  api_v1_task: {
    one_task: (task_id: number) => `/api/v1/task/tasks/${task_id}`,
    task_list: '/api/v1/task/tasks/list',
    task_importVerify: (task_id: number) => `/api/v1/task/tasks/importVerify/${task_id}`,
  },
  api_v1_mge: {
    db_tree: 'api/v1/mge/db/tree',
    db_info: (id: number) => `api/v1/mge/db/detail/${id}`,
  },
  api_v2_storage: {
    get_data: (oid: number) => `/api/v2/storage/data/${oid}`,
    review_data: (meta_id: number) => `/api/v2/storage/data/${meta_id}/review`,
    review_data_history: (history_id: number) => `/api/v2/storage/data/histories/${history_id}/review`,
    review_data_refuse: 'http://lsf.nmdms.ustb.edu.cn/backstage/sourcedata/reportCallback',
    data_withdraw: 'http://cache.nmdms.ustb.edu.cn/admin/interface!returnExample.action', // 高通量计算数据撤回
    review_withdraw: (history_id: number) => `/api/v2/storage/data/histories/${history_id}/revoke`, // 撤回
    template_names: '/api/v2/storage/template/names',
    review_template: (tpl_id: number) => `/api/v2/storage/template/review/state/${tpl_id}`,
    o_data_full_one: (oid: number) => `/api/v2/storage/o/data/full/${oid}`,
    get_history_data: (history_id: number) => `/api/v2/storage/data/histories/${history_id}`,
  },
  api_v2_search: {
    q: '/api/v2/search/q', //
    q_fulltext: '/api/v2/search/q/fulltext', //
    query_list: '/api/v2/search/query/',
    convert_query_list: '/api/v2/search/convert_query', // 南大通用检索
    query_total: (pk: string) => `/api/v2/search/query/${pk}`,
    query_template_detail: (pk: string, template_id: number) => `/api/v2/search/query/${pk}/${template_id}`,
    query_download: (pk: number) => `/api/v2/search/query/${pk}/download`,
    query_download_template: (pk: number, template_id: number) => `/api/v2/search/query/${pk}/${template_id}/download`,
    query_datails: (pk: number, key: string) => `/api/v2/search/querys/${pk}/${key}` //川大跳转
  },
  api_v3_storage: {
    manage_one_data_by_data_manager: (meta_id: number) => `/api/v3/storage/data/${meta_id}`,
    manage_data_by_data_manager: '/api/v3/storage/data/',
    create_dataset: '/api/v3/storage/dataset',
    manage_dataset_one: (id: number) => `/api/v3/storage/dataset/${id}`,
    register_doi: '/api/v3/storage/doi',
    material_method: '/api/v3/storage/material/method',
    upload_list: '/api/v3/storage/upload',
    account_upload_history: '/api/v3/account/me/uploads/',
    modify_pubdate: '/api/v3/account/me/uploads/public', //上传历史页面修改公开时间
    upload_detail: (pk: number) => `/api/v3/storage/upload/${pk}`,
    templates_list: '/api/v3/storage/templates',
    templates_detail: (pk: number) => `/api/v3/storage/templates/${pk}`,
    review_doi_list: '/api/v3/storage/dataset/doiRegisterInfo',
    get_public_range: '/api/v3/storage/data/publicRange',
    create_snippets: '/api/v3/storage/snippets',//上传模板片段（模板嵌套）
    get_snippets: '/api/v3/storage/snippets',//获取用户创建的模板片段
    edit_snippets: (id: number) => `/api/v3/storage/snippets/${id}`,//修改模板片段
    get_snippets_one: (id: number) => `/api/v3/storage/snippets/${id}`,//获取模板片段信息
  },
  api_v3_account: {
    upload_list: (format: string) => `/api/v3/account/admin_category.${format}/?`,
    upload_detail: (pk: string, format: string) => `/api/v3/account/admin_category/${pk}.${format}/?`,
    api_root: (format: string) => `/api/v3/account/.${format}/?`,
  },
  api_v1_project: {
    subject_members: (project_id: string, subject_id: string) => `/api/v1/project/${project_id}/subjects/${subject_id}/users`,
    move_out_member: (subject_id: string, username: string) => `/api/v1/account/users/subjects/${subject_id}/subject_users?username=${username}`,
  },
  training: {
    video_introduction: '/media/mgedata/_docs/train/%E7%AC%AC%E4%B8%80%E8%AE%B2%EF%BC%9A%E6%9D%90%E6%96%99%E5%9F%BA%E5%9B%A0%E5%B7%A5%E7%A8%8B%E4%B8%93%E7%94%A8%E6%95%B0%E6%8D%AE%E5%BA%93%E5%B9%B3%E5%8F%B0%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D.mp4',
    video_tem1: '/media/mgedata/_docs/train/%E7%AC%AC%E4%BA%8C%E8%AE%B2%EF%BC%9A%E6%A8%A1%E6%9D%BF%E5%AE%9A%E4%B9%89%EF%BC%88%E4%B8%8A%EF%BC%89.mp4',
    video_tem2: '/media/mgedata/_docs/train/%E7%AC%AC%E4%BA%8C%E8%AE%B2%EF%BC%9A%E6%A8%A1%E6%9D%BF%E5%AE%9A%E4%B9%89%EF%BC%88%E4%B8%8B%EF%BC%89.mp4',
    video_data: '/media/mgedata/_docs/train/%E7%AC%AC%E4%B8%89%E8%AE%B2%EF%BC%9A%E6%95%B0%E6%8D%AE%E4%B8%8A%E4%BC%A0.mp4',
    file_introduction_PDF: '/media/mgedata/_docs/train/20200103_%E6%95%B0%E6%8D%AE%E6%B1%87%E4%BA%A4%E8%A7%84%E8%8C%83%E4%BB%8B%E7%BB%8D-%E6%9C%80%E7%BB%88%E7%89%88.pdf',
    file_data_XLSX: '/media/mgedata/_docs/train/MGE%E7%B3%BB%E7%BB%9F%E6%BC%94%E7%A4%BA%E6%95%B0%E6%8D%AE.xlsx',
    file_introduction_PPTX: '/media/mgedata/_docs/train/%E7%AC%AC%E4%B8%80%E8%AE%B2%EF%BC%9A%E6%9D%90%E6%96%99%E5%9F%BA%E5%9B%A0%E5%B7%A5%E7%A8%8B%E4%B8%93%E7%94%A8%E6%95%B0%E6%8D%AE%E5%BA%93%E5%B9%B3%E5%8F%B0%E5%8A%9F%E8%83%BD%E4%BB%8B%E7%BB%8D.pptx',
    file_manual_PDF: '/media/mgedata/_docs/train/%E6%95%B0%E6%8D%AE%E6%B1%87%E4%BA%A4%E5%9F%B9%E8%AE%AD%E4%BC%9A%E6%89%8B%E5%86%8C.pdf',
  },
  client: {
    version1: '/media/mgedata/_fs/data_files/2020/06/16/MGE-win32-x64_2020-24-19_V1.20200616151127.rar',
  },
  api_cert: {
    apply_certification: '/api/cert/certificates/',
    apply_verification: '/api/cert/acceptances/',
    get_group_leaders: '/api/cert/groupleaders/',
    get_certification_list: '/api/cert/certificates/',
    get_verification_list: '/api/cert/acceptances/',
    get_certificate: (cert_key: string) => `/api/cert/certificates/${cert_key}`,
    download_data: (cert_key: string) => `/api/cert/certificates/${cert_key}/data`,
    acceptances_list: `/api/cert/acceptances`,
    delete_verification: (id: string) => `/api/cert/acceptances/${id}/`,
    confirm_notification: (id: number) => `/api/v1/account/notifications/${id}/`,
    experts_list: `/api/cert/experts`,
    assign_experts: `/api/cert/dispatches`,
    acceptance_experts: (id: number) => `/api/cert/dispatches/${id}`,
    signature: (id: number) => `/api/cert/acceptances/${id}/signatures`,
    upload_evaluation: '/api/cert/evaluations/',
    evaluation_list: '/api/cert/dispatches',
    evaluation_point: '/api/cert/evaluations/points',
    evaluation_result: '/api/cert/evaluations/',
    export_evaluation: (cert_key: string) => `/cert/${cert_key}/evaluation_pdf`,
    evaluation_filter: '/api/cert/evaluations/filter', // 获取过滤信息（专家）
    acceptance_filter: '/api/cert/acceptances/filter', // 获取过滤信息（负责人）
    evaluation_data: '/api/cert/acceptances/data', // 查看验收数据
    evalucation_judge:(acceptance_id:number)=>`/api/cert/templates/go_next_or_not/${acceptance_id}`,
    evalucation_score:(acceptance_id:number)=>`/api/cert/templates/expert_avg_score/${acceptance_id}`,
  },
  history_log: {
    get_history: '/api/history',
  },
  api_v4_storage: {
    sjg: '/api/v4/storage/sjg/import'
  },
  expert_scoring: '/api/cert/templates',
  uploading_scoring: '/api/cert/templates/score',
  site_index: '/',
  login_mge:'/account/login_mge',
  search_page:'/search',
  NMDMS_site_index: 'http://nmdms.ustb.edu.cn',
  NMDMS_site_index_20: 'http://mged.nmdms.ustb.edu.cn/account/login_mge/',
  site_help: '/help',
  app_entrance: '/app_entrance',
  microscope: '/app_entrance/microscope',
  site_set_language: '/set-language',
  site_urls: '/get-urls',
  javascript_catalog: '/jsi18n/',
  dashboard: '/dashboard/',
  // about: '/about/',
  about: 'http://60.205.217.38:8080/#/home/connectus',
  project: '/project/',
  big_file: (path: string) => `/external/bigfile/api/${path}`,
  bigFile_confirm: '/api/v1/storage/file/bigfile/confirm',
  feedback_list:'/api/v1/ticketing/list_tickets',
  //联邦计算相关
  federated:{
    TaskManagement:'/federated',
    uploaddataset:'/dataset_upload'
  }
};
export default Urls;
